# Generated by Django 3.0.5 on 2022-04-02 13:53

import air_stations.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirStation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('town_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('messures', djongo.models.fields.EmbeddedField(model_container=air_stations.models.Messures)),
                ('air_quality', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('argument', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arguments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('town_id', models.IntegerField()),
                ('argument_type', models.CharField(max_length=30)),
                ('arguments', djongo.models.fields.ArrayField(model_container=air_stations.models.Argument)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Messures',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('so2_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('co_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('no_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('no2_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('pm2_5_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('pm10_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('nox_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('o3_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('tol_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('btx_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ebe_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('mxy_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('pxy_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('oxy_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('tch_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ch4_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('nmhc_messure', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessuresQuality',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('messure_name', models.CharField(max_length=15)),
                ('very_good', models.IntegerField()),
                ('good', models.IntegerField()),
                ('mediocre', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('very_bad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('country', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('url', models.URLField()),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('province', models.IntegerField(null=True)),
            ],
        ),
    ]
