# Generated by Django 3.0.5 on 2021-11-30 18:23

import air_stations.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirStation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('messures', djongo.models.fields.EmbeddedField(model_container=air_stations.models.Messures)),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('argument', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arguments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('town_id', models.IntegerField()),
                ('argument_type', models.CharField(max_length=30)),
                ('arguments', djongo.models.fields.ArrayField(model_container=air_stations.models.Argument)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Messures',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('no2_messure', models.IntegerField(null=True)),
                ('so2_messure', models.IntegerField(null=True)),
                ('co_messure', models.IntegerField(null=True)),
                ('pm10_messure', models.IntegerField(null=True)),
                ('pm2_5_messure', models.IntegerField(null=True)),
                ('o3_messure', models.IntegerField(null=True)),
                ('btx_messure', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('country', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('air_stations', djongo.models.fields.ArrayField(model_container=air_stations.models.AirStation)),
                ('url', models.URLField()),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('province', models.IntegerField(null=True)),
            ],
        ),
    ]
