# Generated by Django 3.0.5 on 2021-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessuresQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messure_name', models.CharField(max_length=15)),
                ('very_good', models.IntegerField()),
                ('good', models.IntegerField()),
                ('mediocre', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('very_bad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='airstation',
            name='air_quality',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='ch4_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='ebe_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='mxy_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='nmhc_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='no_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='nox_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='oxy_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='pxy_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='tch_messure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messures',
            name='tol_messure',
            field=models.IntegerField(null=True),
        ),
    ]
