# Generated by Django 3.0.5 on 2021-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_stations', '0003_auto_20211226_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessuresQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messure_name', models.CharField(max_length=15)),
                ('very_good', models.IntegerField()),
                ('good', models.IntegerField()),
                ('mediocre', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('very_bad', models.IntegerField()),
            ],
        ),
    ]
