# Generated by Django 3.0.5 on 2021-12-26 16:49

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('air_stations', '0004_messuresquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messuresquality',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
