# Generated by Django 3.0.5 on 2021-12-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_stations', '0006_airstation_town_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airstation',
            name='town_id',
            field=models.IntegerField(),
        ),
    ]
