# Generated by Django 3.0.5 on 2022-02-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_stations', '0007_auto_20211229_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airstation',
            old_name='town_id',
            new_name='town',
        ),
    ]
