# Generated by Django 3.0.5 on 2022-02-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_stations', '0008_auto_20220226_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airstation',
            old_name='town',
            new_name='town_id',
        ),
        migrations.RemoveField(
            model_name='town',
            name='air_stations',
        ),
    ]
