from routes.models import Route

def generate_routes_testing_data():
    #Route for check that don't appear with the principal user
    Route.objects.create(   user = 'othertestinguser@othertestinguser.com',  
                            distance = 50, 
                            time = 0, 
                            nodes =[{'id':1, 'latitude':40.410836, 'longitude':-3.724539, 'air_quality':None},
                                    {'id':2, 'latitude':40.411685, 'longitude':-3.724225, 'air_quality':None}],
                            very_good_air_quality_nodes = 0,
                            good_air_quality_nodes = 0,
                            mediocre_air_quality_nodes = 0,
                            bad_air_quality_nodes = 0,
                            very_bad_air_quality_nodes = 0,
                            unknown_air_quality_nodes = 0,
                            ranking_puntuation = 50)
    #First route that should appear when ordering by date asc and last route that should appear when ordering by date desc
    Route.objects.create(   user = 'testing@testing.com', 
                            distance = 50, 
                            time = 1, 
                            nodes =[{'id':1, 'latitude':40.410836, 'longitude':-3.724539, 'air_quality':None},
                                    {'id':2, 'latitude':40.411685, 'longitude':-3.724225, 'air_quality':None}],
                            very_good_air_quality_nodes = 1,
                            good_air_quality_nodes = 1,
                            mediocre_air_quality_nodes = 1,
                            bad_air_quality_nodes = 1,
                            very_bad_air_quality_nodes = 1,
                            unknown_air_quality_nodes = 1,
                            ranking_puntuation = 50)
    #First route that should appear when ordering by ranking_puntuation
    Route.objects.create(   user = 'testing@testing.com', 
                            distance = 50, 
                            time = 2, 
                            nodes =[{'id':1, 'latitude':40.410836, 'longitude':-3.724539, 'air_quality':None},
                                    {'id':2, 'latitude':40.411685, 'longitude':-3.724225, 'air_quality':None}],
                            very_good_air_quality_nodes = 2,
                            good_air_quality_nodes = 2,
                            mediocre_air_quality_nodes = 2,
                            bad_air_quality_nodes = 2,
                            very_bad_air_quality_nodes = 2,
                            unknown_air_quality_nodes = 2,
                            ranking_puntuation = 100)
    #Last route that should appear when ordering by ranking_puntuation
    Route.objects.create(   user = 'testing@testing.com', 
                            distance = 50, 
                            time = 3, 
                            nodes =[{'id':1, 'latitude':40.410836, 'longitude':-3.724539, 'air_quality':None},
                                    {'id':2, 'latitude':40.411685, 'longitude':-3.724225, 'air_quality':None}],
                            very_good_air_quality_nodes = 3,
                            good_air_quality_nodes = 3,
                            mediocre_air_quality_nodes = 3,
                            bad_air_quality_nodes = 3,
                            very_bad_air_quality_nodes = 3,
                            unknown_air_quality_nodes = 3,
                            ranking_puntuation = 0)
    #First route that should appear when ordering by distance
    Route.objects.create(   user = 'testing@testing.com',  
                            distance = 100, 
                            time = 4, 
                            nodes =[{'id':1, 'latitude':40.410836, 'longitude':-3.724539, 'air_quality':None},
                                    {'id':2, 'latitude':40.411685, 'longitude':-3.724225, 'air_quality':None}],
                            very_good_air_quality_nodes = 4,
                            good_air_quality_nodes = 4,
                            mediocre_air_quality_nodes = 4,
                            bad_air_quality_nodes = 4,
                            very_bad_air_quality_nodes = 4,
                            unknown_air_quality_nodes = 4,
                            ranking_puntuation = 50)
    #Last route that should appear when ordering by distance
    Route.objects.create(   user = 'testing@testing.com', 
                            distance = 0, 
                            time = 5, 
                            nodes =[{'id':1, 'latitude':40.410836, 'longitude':-3.724539, 'air_quality':None},
                                    {'id':2, 'latitude':40.411685, 'longitude':-3.724225, 'air_quality':None}],
                            very_good_air_quality_nodes = 5,
                            good_air_quality_nodes = 5,
                            mediocre_air_quality_nodes = 5,
                            bad_air_quality_nodes = 5,
                            very_bad_air_quality_nodes = 5,
                            unknown_air_quality_nodes = 5,
                            ranking_puntuation = 50)
    #Last route that should appear when ordering by date asc and first route that should appear when ordering by date desc
    Route.objects.create(   user = 'testing@testing.com',
                            distance = 50, 
                            time = 6, 
                            nodes =[{'id':1, 'latitude':40.410836, 'longitude':-3.724539, 'air_quality':None},
                                    {'id':2, 'latitude':40.411685, 'longitude':-3.724225, 'air_quality':None}],
                            very_good_air_quality_nodes = 6,
                            good_air_quality_nodes = 6,
                            mediocre_air_quality_nodes = 6,
                            bad_air_quality_nodes = 6,
                            very_bad_air_quality_nodes = 6,
                            unknown_air_quality_nodes = 6,
                            ranking_puntuation = 50)