# Generated by Django 3.0.5 on 2022-04-02 13:52

from django.db import migrations, models
import djongo.models.fields
import routes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('text', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
                ('air_quality', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.EmailField(max_length=60)),
                ('date_saved', models.DateTimeField(auto_now=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.IntegerField()),
                ('instructions', djongo.models.fields.ArrayField(model_container=routes.models.Instruction, null=True)),
                ('nodes', djongo.models.fields.ArrayField(model_container=routes.models.Node)),
                ('very_good_air_quality_nodes', models.IntegerField()),
                ('good_air_quality_nodes', models.IntegerField()),
                ('mediocre_air_quality_nodes', models.IntegerField()),
                ('bad_air_quality_nodes', models.IntegerField()),
                ('very_bad_air_quality_nodes', models.IntegerField()),
                ('unknown_air_quality_nodes', models.IntegerField()),
                ('ranking_puntuation', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
