# Generated by Django 3.0.5 on 2022-01-06 20:50

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('air_quality', models.IntegerField()),
                ('surface_quality', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteRanking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.EmailField(max_length=60, null=True)),
            ],
        ),
    ]
