# Generated by Django 3.0.5 on 2022-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20220108_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteRanking',
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.EmailField(max_length=60, null=True),
        ),
    ]
