# Generated by Django 3.0.5 on 2022-01-09 18:37

from django.db import migrations, models
import djongo.models.fields
import routes.models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20220109_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('distance', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
                ('text', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='instructions',
            field=djongo.models.fields.ArrayField(model_container=routes.models.Instruction, null=True),
        ),
    ]
