# Generated by Django 3.0.5 on 2022-01-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20220109_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bad_air_quality_nodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='good_air_quality_nodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='mediocre_air_quality_nodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='nodes_on_green_areas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='nodes_on_non_green_areas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='very_bad_quality_nodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='very_good_air_quality_nodes',
            field=models.IntegerField(null=True),
        ),
    ]
