# Generated by Django 3.0.5 on 2022-01-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20220121_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='very_bad_quality_nodes',
            new_name='very_bad_air_quality_nodes',
        ),
        migrations.AddField(
            model_name='route',
            name='unknown_air_quality_nodes',
            field=models.IntegerField(null=True),
        ),
    ]
