# Generated by Django 3.0.5 on 2022-01-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20220121_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date_saved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
