# Generated by Django 3.0.5 on 2022-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20220123_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
