# Generated by Django 3.0.5 on 2022-01-23 12:55

from django.db import migrations, models
import djongo.models.fields
import routes.models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_auto_20220123_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='bad_air_quality_nodes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='route',
            name='good_air_quality_nodes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='mediocre_air_quality_nodes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='nodes',
            field=djongo.models.fields.ArrayField(model_container=routes.models.Node),
        ),
        migrations.AlterField(
            model_name='route',
            name='ranking_puntuation',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='route',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='unknown_air_quality_nodes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='route',
            name='very_bad_air_quality_nodes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='very_good_air_quality_nodes',
            field=models.IntegerField(),
        ),
    ]
