# Generated by Django 3.0.5 on 2022-01-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_auto_20220123_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
