# Generated by Django 3.0.5 on 2022-01-23 17:31

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_auto_20220123_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='id',
        ),
        migrations.AddField(
            model_name='route',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
