# Generated by Django 3.0.5 on 2022-01-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_auto_20220123_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='route',
            name='ranking_puntuation',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
