# Generated by Django 3.0.5 on 2022-02-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0018_auto_20220227_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='surface_quality',
        ),
    ]
